services:
  mysql:
    image: mysql:8.4
    container_name: public-service-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: public_service
      MYSQL_USER: public_user
      MYSQL_PASSWORD: public1234

    ports:
      - "13306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: