spring.application.name=public-service

spring.datasource.url=jdbc:mysql://localhost:13306/public_service
spring.datasource.username=public_user
spring.datasource.password=public1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true